- name: configure the databese server 
  hosts: all
  become: yes
  tasks: 
  - name: install packages 
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum:
      name:
      - python
      - python3
      - pip
      - docker
      - vim
      - net-tools
      - mysql-server
      - mysql
      - bash-completion.noarch      
      update_cache: yes
      state: present
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/bashrc
      block: |
        alias c=clear
        alias k=kubectl         
  - name: start & enable mysqld
    systemd: 
      name: mysqld
      state: started
      enabled: true      
  - name: Install docker mysql module
    vars:
      ansible_python_interpreter: /usr/bin/python
    pip: 
      name: 
      - mysql-connector 
      - PyMySQL           
  - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
    community.mysql.mysql_user:
      name: iti
      password: iti
      priv: '*.*:ALL,GRANT'
      state: present
      host: '%'
  - name: Removes all anonymous user accounts
    community.mysql.mysql_user:
      name: 'iti'
      host_all: true
      state: present      
  - name: Set a hostname
    ansible.builtin.hostname:
      name: db-server   
  - name: Reconnect to server session
    meta: reset_connection      
  - name: Create a new database with name 'iti'
    community.mysql.mysql_db:
      name: iti
      state: present
  - name: Run several insert queries against db test_db in single transaction
    community.mysql.mysql_query:
      login_db: iti
      query:
      - create table userinfo (id int not null auto_increment, firstname varchar(25), lastname varchar(25), age int, email varchar(40) ,constraint c1 primary key (id))
