- name: Configure httpd server
  hosts: all
  become: yes
  tasks: 
  - name: install packages 
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum:
      name:
      - python
      - python3
      - pip
      - docker
      - httpd
      - vim
      - net-tools
      #- mysql-server   --> will deploy the database on a separate dedicated server
      - mysql
      - bash-completion.noarch      
      update_cache: yes
      state: present
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/bashrc
      block: |
        alias c=clear
        alias k=kubectl         
  - name: start & enable httpd
    systemd: 
      name: httpd
      state: started
      enabled: true   
  - name: Install the php remote repo
    ansible.builtin.dnf:
      name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'
      state: present
      disable_gpg_check: true
  - name : enable dnf module enable php
    command: dnf module -y enable php
  - name: Install the latest version of Apache from the testing repo
    ansible.builtin.dnf:
      name:
      - php 
      - php-cli 
      - php-common
      - php-mysqlnd
  - name: Copy html files
    copy:
      src: /home/ahmed/Desktop/terraform/fully-automated-website-with-database-using-terraform-ansible/redhat/html_files/
      dest: /var/www/html/
  - name: Set a hostname
    ansible.builtin.hostname:
      name: http      
  - name: Reload service httpd
    ansible.builtin.systemd:
      name: httpd.service
      state: restarted  
  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    ansible.posix.selinux:
      policy: targeted
      state: permissive
